# Generated by Django 2.1.2 on 2019-11-20 13:39

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191118_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[utils.validators.validate_file_size, utils.validators.validate_extension]),
        ),
    ]
