# Generated by Django 2.1.2 on 2019-12-03 18:44

from django.db import migrations, models
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191120_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=utils.upload.user_avatar_path, validators=[utils.validators.validate_file_size, utils.validators.validate_extension]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='users.University'),
        ),
    ]
