# Generated by Django 2.1.2 on 2019-12-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191204_0738'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activation',
            managers=[
            ],
        ),
    ]
