# Generated by Django 2.1.2 on 2019-11-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191106_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
