# Generated by Django 2.1.2 on 2019-11-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191117_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
